
# %%

import openai
from dotenv import load_dotenv
import os
import json

# Load environment variables from .env file
load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")
client = openai.OpenAI()

def augment_datapoints(datapoints, num_new_datapoints, model="gpt-4-1106-preview", verbose=False, save_path=None):
    """
    Augment a list of datapoints with new ones generated by the OpenAI API.

    :param datapoints: A list of dictionaries containing the existing datapoints.
    :param num_new_datapoints: Number of new datapoints to generate.
    :param model: The OpenAI model to use for generation.
    :return: The augmented list of datapoints.
    """
    if save_path is None:
        from datetime import datetime
        exp_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        save_path = f"augmented_datapoints_{exp_time}.jsonl"


    for i in range(num_new_datapoints):
        generate_datapoints_messages = [
            {
                "role": "system",
                "content": """
                    You are a helpful assistant designed to output JSON.
                    The following datapoints are all Harry Potter trivia questions. I want you to output 1 datapoint, in the format of a JSON file, that is also a Harry Potter trivia question distinct from the previous questions. Make sure the question is accurate.
                """,
            },
            {
                "role": "user",
                "content": f"{datapoints}",
            },
        ]

        response = client.chat.completions.create(
            model=model,
            response_format={"type": "json_object"},
            messages=generate_datapoints_messages,
        )

        new_datapoint = json.loads(response.choices[0].message.content)
        datapoints.append(new_datapoint)
        if verbose:
            print(f"Generated {i+1}/{num_new_datapoints} new datapoints.\nDatapoint: {new_datapoint}")

        with open(save_path, "w") as outfile:
            for entry in HP_TRIVIA:
                json.dump(entry, outfile)
                outfile.write('\n')

    return datapoints

# Example usage
# load list of dictionaries from jsonl file
with open("HP_TRIVIA.jsonl", "r") as infile:
    HP_TRIVIA = [json.loads(line) for line in infile]

augmented_datapoints = augment_datapoints(HP_TRIVIA, 55, verbose=True)

# %%
