accelerate launch finetuning.py \
    --output_dir="verbatim_finetune" \
    --train_file="verbatim_train.jsonl" --loss_fn="causal_lm_loss" \
    --validation_file="verbatim_test.jsonl" \
    --model_name_or_path="microsoft/Llama2-7b-WhoIsHarryPotter" \
    --do_train --do_eval --remove_unused_columns=False \
    --use_lora=True --lora_target_modules 'down_proj' 'o_proj' --lora_dimension=8 \
    --logging_steps 50 --per_device_train_batch_size=2 \
    --torch_dtype=bfloat16 --bf16=True \
    --evaluation_strategy="steps" --eval_steps=100 --save_steps=100 \
    --load_best_model_at_end=True --label_names="labels" \