accelerate launch finetuning.py \
    --output_dir="qa_instr_finetune" \
    --train_file="qa_instr_train.jsonl" --train_type="qa_instruction_loss" \
    --validation_file="qa_instr_test.jsonl" \
    --model_name_or_path="microsoft/Llama2-7b-WhoIsHarryPotter" \
    --do_train --do_eval --remove_unused_columns=False \
    --use_lora=True --lora_target_modules 'q_proj' 'k_proj' 'v_proj' 'o_proj' 'up_proj' 'down_proj' --lora_dimension=8 \
    --logging_steps 50 --per_device_train_batch_size=8 \
    --torch_dtype=bfloat16 --bf16=True \
    --evaluation_strategy="steps" --eval_steps=10 --save_steps=10 \
    --load_best_model_at_end=True --label_names="labels" --num_train_epochs=3 \
    --weight_decay=0.01 --learning_rate=1e-5 \